### ISSUE TITLE
[langchain-sqlserver] Error when inserting a lot of documents

### ISSUE THREAD

**Issue by yorek** [langchain-ai/langchain-azure#11]
When adding a lot of documents to the vectorstore using the `from_documents` function, I get the following error:

```
2024-12-02 11:02:35,662 - ERROR - Add text failed:
 ('07002', '[07002] [Microsoft][ODBC Driver 18 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')

Traceback (most recent call last):
  File "W:\_git\_owned\azure-sql-langchain\samples\agentic-rag.py", line 47, in <module>
    vector_store = SQLServer_VectorStore.from_documents(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\_git\_owned\azure-sql-langchain\.venv\Lib\site-packages\langchain_sqlserver\vectorstores.py", line 578, in from_documents
    store.add_texts(texts, metadatas, ids, **kwargs)
  File "W:\_git\_owned\azure-sql-langchain\.venv\Lib\site-packages\langchain_sqlserver\vectorstores.py", line 836, in add_texts
    return self._insert_embeddings(texts, embedded_texts, metadatas, ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\_git\_owned\azure-sql-langchain\.venv\Lib\site-packages\langchain_sqlserver\vectorstores.py", line 1239, in _insert_embeddings     
    raise Exception(e.__cause__) from None
Exception: ('07002', '[07002] [Microsoft][ODBC Driver 18 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')
```

It seems that if I try to insert less than 500 documents it works fine. With more it just return the above error.

**Comment by anushakolan** [comment]
Inserting 527 documents is giving this error
<img width="1551" alt="Image" src="https://github.com/user-attachments/assets/7fd751ad-19e7-41e2-bea7-a2ec0ce39513" />

**Comment by anushakolan** [comment]
526 is giving same error as 527 documents
<img width="1542" alt="Image" src="https://github.com/user-attachments/assets/041f1acc-a890-43c6-ab88-c830e6da17a4" />

**Comment by anushakolan** [comment]
But inserting 525 documents is giving a different error message,

`ERROR    root:vectorstores.py:1308 Add text failed:
 ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request. (8003) (SQLExecDirectW)')`

<img width="1538" alt="Image" src="https://github.com/user-attachments/assets/a95fb233-c8c3-4b88-8290-46c6ecd7ea78" />

**Comment by anushakolan** [comment]
Now inserting 524 documents is working fine,

<img width="1543" alt="Image" src="https://github.com/user-attachments/assets/ed543fa6-b3cd-40de-bd76-80a0c808d772" />

**Comment by yorek** [comment]
Tested and it all work nicely!
