### ISSUE TITLE
pydantic errors when binding tools to model

### ISSUE THREAD

**Issue by dennisseah** [langchain-ai/langchain-azure#18]
OS: macOS Sequoia
Python 3.12.1

# dependencies
```
langchain-core = "^0.3.28"
langchain-azure-ai = "^0.1.0"
python-dotenv = "^1.0.1"
```

# Issue:
Pydantic validation errors appear after model is bind with tools. Here is the code to reproduce the problem

```
import os

from azure.identity import DefaultAzureCredential
from langchain_azure_ai.chat_models import AzureAIChatCompletionsModel
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import PromptTemplate
from langchain_core.tools import tool


def get_model():
    credential = (
        DefaultAzureCredential()
        .get_token("https://cognitiveservices.azure.com/.default")
        .token
    )

    return AzureAIChatCompletionsModel(
        endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
        credential=credential,
        api_version=os.environ["AZURE_OPENAI_API_VERSION"],
        model_name=os.environ["AZURE_OPENAI_DEPLOYED_MODEL_NAME"],
        temperature=0,
        client_kwargs={"logging_enable": True},
    )


def get_template() -> PromptTemplate:
    return PromptTemplate(
        template="calculate the following expression: {expression}",
        input_variables=["expression"],
    )


# without tools binding is ok
chain = get_template() | get_model() | StrOutputParser()
response = chain.invoke({"expression": "1+3"})
print(response)


@tool
def add(a: int, b: int) -> int:
    """Add two numbers together"""
    return a + b


# with tools binding got errors
model = get_model().bind_tools([add])
chain = get_template() | model | StrOutputParser()
response = chain.invoke({"expression": "1+3"})
print(response)
```

# stacktrace

```
Traceback (most recent call last):
  File "/Users/dennisseah/git/az-langchain/bug.py", line 43, in <module>
    response = chain.invoke({"expression": "1+3"})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3024, in invoke
    input = context.run(step.invoke, input, config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 5354, in invoke
    return self.bound.invoke(
           ^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 286, in invoke
    self.generate_prompt(
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 786, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 643, in generate
    raise e
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 633, in generate
    self._generate_with_cache(
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 851, in _generate_with_cache
    result = self._generate(
             ^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_azure_ai/chat_models/inference.py", line 463, in _generate
    return self._create_chat_result(response)  # type: ignore[arg-type]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_azure_ai/chat_models/inference.py", line 431, in _create_chat_result
    message = from_inference_message(res.message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_azure_ai/chat_models/inference.py", line 140, in from_inference_message
    return AIMessage(content=message.content, additional_kwargs=additional_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/messages/ai.py", line 179, in __init__
    super().__init__(content=content, **kwargs)
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/messages/base.py", line 76, in __init__
    super().__init__(content=content, **kwargs)
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/langchain_core/load/serializable.py", line 125, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/dennisseah/git/az-langchain/.venv/lib/python3.12/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 2 validation errors for AIMessage
content.str
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.10/v/string_type
content.list[union[str,dict[any,any]]]
  Input should be a valid list [type=list_type, input_value=None, input_type=No
```

**Comment by santiagxf** [comment]
Thanks for reporting this bug @dennisseah! We rooted the problem to certain OpenAI models where `content` is `None` when a tool call is performed. LangChain requires the content to have a value and hence it triggers the validation error. This bugfix is being shipped very soon.

**Comment by santiagxf** [comment]
Fixed https://github.com/langchain-ai/langchain-azure/pull/32/
